#ifndef INCLUDE_CONFIGURATION_H
#define INCLUDE_CONFIGURATION_H

// Control flags
#define PROFILE 1
#define PROFILE_RX_ERROR 0
#define TPSYNC_ENABLE 1
#define TPSYNC_DELAY_TX_ENABLE 0

#endif /* INCLUDE_CONFIGURATION_H */
